[package]
name = "crypto"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
pqcrypto-falcon = { version = "0.4.0", features = ["avx2"] }
pqcrypto-mlkem = { version = "0.1.0", features = ["avx2"] }
pqcrypto-traits = "0.3.5"
chacha20poly1305 = "0.10.1"
crypto-common = "0.1.6"